customadmin/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('users',views.userlist,name='user_list'),
    path('users/create',views.createuser,name='user_create'),
    path('createuser/<int:user_id>/', views.createuser, name='update_user'),
    
    path('leave_type',views.leave_type,name='leave_type'),
    path('leave_type/create',views.createleave_type,name='leave_type_create'),
    path('leave_type_update/<int:leave_id>/',views.createleave_type,name='leave_type_update'),
    path('leave_type_delete/<int:leave_id>/',views.delete_leave_type,name='leave_type_delete'),
    path('leaveresponse/', views.leaveresponse, name='leaveresponse'),
    path('leavedel/', views.leavedel, name='leavedel'),
    path('leave',views.leave,name='leave'),
    path('approve_leave/<int:pk>', views.approve_leave, name='approve_leave'),
    path('reject_leave/<int:pk>', views.reject_leave, name='reject_leave'),
    path('attandance/<int:pk>', views.attandance, name='attandance'),

]

employee/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('checkin', views.check_in, name='checkin'),
    path('checkout', views.check_out, name='checkout'),
    path('leave', views.leave_list, name='leave'),
    path('leave/create', views.apply_leave, name='leave_apply'),
    path('profile',views.profile,name='profile'),

    
    ]

hrms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',views.index,name='index'),
    path('user/',include(('users.urls','user'),namespace='user')),
    path('admin/',include(('customadmin.urls','customadmin'),namespace='customadmin')),
    path('employe/',include(('employee.urls','employe'),namespace='employe')),
    path('user/', include('django.contrib.auth.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/employe/apply_leave.html
{% extends 'employe/basic.html' %} 
{% load static %}

    {% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/forms/select/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css' %}">
    <!-- END: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/forms/pickers/form-flat-pickr.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/forms/form-validation.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/app-user.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.9.0/dist/css/bootstrap-datepicker.min.css">

    {% endblock style %}
</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu-modern  navbar-floating footer-static  " data-open="click" data-menu="vertical-menu-modern" data-col="">
    {% block content %}


        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper container-xxl p-0">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <!-- users edit start -->
                <section class="app-user-edit">
                    <div class="card">
                        <div class="card-body">
                            <div class="tab-content">
                                {% if messages %}
                                {% for message in messages %}
                                    {% if message.tags == 'error' %}
                                <div class="alert alert-danger" role="alert">
                                    {{message}}
                                </div>
                                    {% else %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{message}}
                                </div>
                                    {% endif %}
                                {% endfor %}{% endif %}
                                <div class="row">
                                    <div class="col-md-7"></div>
                                    <div class="col-md-2"></div>
                                    <div class="col-md-3">
                                    </div>
                                  
                                <!-- Account Tab starts -->
                                <div class="tab-pane active" id="account" aria-labelledby="account-tab" role="tabpanel">
                                    <form class="form-validate" method="POST">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">Leave Type</label>
                                                    {{form.leave_type}}
                                                    {% comment %} <input type="text" name="first_name" class="form-control" placeholder="First name" value="" id="username" /> {% endcomment %}
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="name">Start Date</label>
                                                    {% comment %} <input type="text" name="last_name" class="form-control" placeholder="Last Name" value="" id="name" /> {% endcomment %}
                                                {{form.start_date}}
                                                {{form.media}}
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="email">End Date</label>
                                                    {{form.end_date}}
                                                    {% comment %} <input type="email" name="email" required class="form-control" placeholder="Email" value="" id="email" /> {% endcomment %}
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="status">Reason</label>
                                                    {{form.reason}}
                                                    {% comment %} <select name="status" class="form-control" id="status">
                                                        <option value="1">Active</option>
                                                        <option value="0">Inactive</option>
                                                    </select> {% endcomment %}
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    {% comment %} <label for="email">Password</label> {% endcomment %}
                                                    {{form.password1.label}}
                                                    {{form.password1}}
                                                    {% comment %} <input type="text" name="password1" required class="form-control" placeholder="Email" value="" id="email" /> {% endcomment %}
                                                </div>
                                            </div><div class="col-md-4">
                                                <div class="form-group">
                                                    {% comment %} <label for="email">confirm Password</label> {% endcomment %}
                                                    {{form.password2.label}}
                                                    {{form.password2}}

                                                    {% comment %} <input type="text" name="password2" required class="form-control" placeholder="Email" value="" id="email" /> {% endcomment %}
                                                </div>
                                            </div>
                                            
                                            {% comment %} <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="role">Role</label>
                                                    <select class="form-control" id="role">
                                                        <option>Admin</option>
                                                        <option>User</option>
                                                        <option>Staff</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="company">Company</label>
                                                    <input type="text" class="form-control" value="WinDon Technologies Pvt Ltd" placeholder="Company name" id="company" />
                                                </div>
                                            </div> {% endcomment %}
                                           
                                            <div class="col-12 d-flex flex-sm-row flex-column mt-2">
                                                <button type="submit" class="btn btn-primary mb-1 mb-sm-0 mr-0 mr-sm-1">Save Changes</button>
                                                <button type="reset" class="btn btn-outline-secondary">Reset</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
                <!-- users edit ends -->

            </div>
        </div>
    <!-- END: Content-->
    {% endblock content %}
    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN Vendor JS-->
    {% block scriptjs %}
       <!-- BEGIN: Page Vendor JS-->
       <script href="{% static 'app-assets/vendors/js/forms/select/select2.full.min.js' %}"></script>
       <script href="{% static 'app-assets/vendors/js/forms/validation/jquery.validate.min.js' %}"></script>
       <script href="{% static 'app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js' %}"></script>
       <!-- END: Page Vendor JS-->
   
       {% comment %} <script src="{% static 'app-assets/js/scripts/forms/form-validation.js' %}"></script> {% endcomment %}

       <!-- BEGIN: Page JS-->
       <script href="{% static 'app-assets/js/scripts/pages/app-user-edit.js' %}"></script>
       <script href="{% static 'app-assets/js/scripts/components/components-navs.js' %}"></script>
       <script src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.9.0/dist/js/bootstrap-datepicker.min.js"></script>

       <!-- END: Page JS-->
    {% endblock scriptjs %}
 

    <script>
        $(window).on('load', function() {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.datepicker').datepicker();
        });
    </script>
</body>
<!-- END: Body-->

</html>

templates/employe/index.html
{% extends 'employe/basic.html' %} 
{% block content %}
{% load tz %}

    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
        </div>
        <div class="content-body">
            <!-- users list start -->
            <section class="app-user-list">
                <div class="row">
                    <div class="col-lg-4 col-sm-6">
                        <div class="card">
                            <div class="card-body d-flex align-items-center justify-content-between">
                                <div>
                                    <h3 class="fw-bolder mb-75">    
                                        {% if check_in_exists %}
                                            {% if check_out_exists %} 
                                            You Already punch Out Today
                                            {% else %}
                                            <a href="{% url "employe:checkout" %}"><button type="button" class="btn btn-primary">Punch out </button></a>
                                            {% comment %} <a href="{% url "employe:checkin" %}"><button type="button" class="btn btn-primary">Punch In </button></a> {% endcomment %}
                                            {% endif %}
                                        {% else %}
                                        <a href="{% url "employe:checkin" %}"> <button type="button" class="btn btn-primary">Punch In </button></a>
                                        {% endif %}
                                    </h3>
                                    <span>check in </span>
                                </div>
                                {% comment %} <div class="avatar bg-light-primary p-50">
                                    <span class="avatar-content">
                                        <i data-feather="user" class="font-medium-4"></i>
                                    </span>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>
                  
                    <div class="col-lg-4 col-sm-6">
                        <div class="card">
                            <div class="card-body d-flex align-items-center justify-content-between">
                                <div>
                                    <h3 class="fw-bolder mb-75">{{total_working_time}} Hours</h3>
                                    <span>Total Working Time</span>
                                </div>
                                <div class="avatar bg-light-danger p-50">
                                    <span class="avatar-content">
                                        <i data-feather="clock" class="font-medium-4"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card">
                            <div class="card-body d-flex align-items-center justify-content-between">
                                <div>
                                    <h3 id="clock" class="fw-bolder mb-75"></h3>
                                    <span>Current Time </span>
                                </div>
                                <div class="avatar bg-light-warning p-50">
                                    <span class="avatar-content">
                                        <i data-feather="clock" class="font-medium-4"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                </div>
                <div class="card">
                        
                    <div class="card-body border-bottom">
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{message}}
                            </div>
                                {% else %}
                            <div class="alert alert-{{ message.tags }}" role="alert">
                                {{message}}
                            </div>
                                {% endif %}
                            {% endfor %}{% endif %}
                        <h4 class="card-title">Attendance: {{month_name|date:"Y F"}}</h4>
                        <div class="row">
                            <div class="col-md-4 user_role">
                                <form id="filterdate001" method="get" >
                                <div class="row">
                                    <div class="col-md-4">
                                        <select name="select_year" id="year" class="form-control">
                                            {% for year in years %}
                                                <option value="{{ year }}" {% if year == current_year %}selected{% endif %}>
                                                    {{ year }}
                                                </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-md-6" style="padding-left: 7px;">
                                        <select name="select_month" id="month" class="form-control">
                                            {% for month, month_name in months %}
                                                <option value="{{ month }}" {% if month == current_month|stringformat:"s" %}selected{% endif %}>
                                                    {{ month_name }}
                                                </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-md-2" style="padding-left: 8px;">                              
                                        <button id="filterdatebtn001" class="btn btn-primary w-80 waves-effect waves-float waves-light" >Filter</button>
                                    </div>
                                </div>
                            </form>
                            </div>
                            <div class="col-md-6 user_plan">
                              {% comment %} <button id="filterdatebtn001" class="btn btn-primary w-80 waves-effect waves-float waves-light" >Filter</button> {% endcomment %}
                            </div>
                            {% comment %} <div class="col-md-2 user_status">
                                <a href="{% url 'customadmin:user_create' %}"><button class="btn btn-primary w-80 waves-effect waves-float waves-light" >Add User</button></a>
                            </div> {% endcomment %}
                        </div>
                    </div>
                    <div class="card-datatable table-responsive pt-0">
                        <table class="user-list-table table">
                            <thead class="table-light">
                                <tr>
                                    <th>date</th>
                                    <th>Attendance</th>
                                    <th>Punch In</th>
                                    <th>Punch Out</th>
                                    <th>Working hours</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in attendance_report %}
                                <tr>
                                    <td>{{i.date}}</td>
                                    <td>{{i.attendance}}</td>
                                    <td>{% if i.check_in_time %}{{i.check_in_time }}{% else %}------{% endif %}</td>
                                    <td>{% if i.check_out_time %}{{i.check_out_time}}{% else %}-------{% endif %}</td>
                                    <td>{% if i.total_working_time %}{{i.total_working_time}} Hours{% else %}0.0 Hours{% endif %}</td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            
            </section>
            <!-- users list ends -->
    
        </div>
    </div>
{% endblock %}
{% block scriptjs %}
<script>
    document.getElementById('filterdatebtn001').addEventListener('click', function() {
        document.getElementById('filterdate001').submit();
    });
  </script>
<script>
    function updateClock() {
        var now = new Date();
        var hours = now.getHours();
        var minutes = now.getMinutes();
        var seconds = now.getSeconds();
        
        // Add leading zero if time is less than 10
        hours = hours < 10 ? '0' + hours : hours;
        minutes = minutes < 10 ? '0' + minutes : minutes;
        seconds = seconds < 10 ? '0' + seconds : seconds;
        
        var timeString = hours + ':' + minutes + ':' + seconds;
        
        // Display the time in the clock div
        document.getElementById('clock').textContent = timeString;
    }

    // Update clock every second
    setInterval(updateClock, 1000);

    // Initialize clock immediately
    updateClock();
</script>
{% endblock scriptjs %}

templates/employe/leave.html
{% extends 'employe/basic.html' %} 
{% block content %}

    <!-- BEGIN: Content-->
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper container-xxl p-0">
        <div class="content-header row">
        </div>
        <div class="content-body">
            <!-- users list start -->
            <section class="app-user-list">
               
            
                <!-- list and filter start -->
                <div class="card">
                    
                    <div class="card-body border-bottom">
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{message}}
                            </div>
                                {% else %}
                            <div class="alert alert-{{ message.tags }}" role="alert">
                                {{message}}
                            </div>
                                {% endif %}
                            {% endfor %}{% endif %}
                        {% comment %} <h4 class="card-title">Search & Filter</h4> {% endcomment %}

                        <div class="row">
                            <div class="col-md-4 user_role">
                              {% comment %} <form id="search001" method="get" >
                              <select class="form-select" name="search" aria-label="Default select example">
                                <option value="1">Active</option>
                                <option value="0">Inactive</option>
                                <option selected> All</option>
                              </select>
                              <!-- <button class="btn btn-primary w-80 waves-effect waves-float waves-light" >Search</button> -->

                            </form> {% endcomment %}
                            </div>
                            <div class="col-md-5 user_plan">
                              {% comment %} <button id="searchbtn001" class="btn btn-primary w-80 waves-effect waves-float waves-light" >Filter</button> {% endcomment %}
                            </div>
                            <div class="col-md-3 user_status">
                                <a href="{% url 'employe:leave_apply' %}"><button class="btn btn-primary w-80 waves-effect waves-float waves-light" >Apply Leave</button></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-datatable table-responsive pt-0">
                        <table class="user-list-table table">
                            <thead class="table-light">
                                <tr>
                                    <th></th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Leave from </th>
                                    <th>Leave to</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in data %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{i.user.first_name}}</td>
                                    <td>{{i.user.last_name}}</td>
                                    <td>{{i.start_date}}</td>
                                    <td>{{i.end_date}}</td>
                                    <td>{{i.status}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- list and filter end -->
            </section>
            <!-- users list ends -->

        </div>
    </div>
{% endblock %}